[package]
name = "stack-resolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deep-trinity-core = { path = "../deep-trinity-core" }
deep-trinity-tree = { path = "../deep-trinity-tree" }
