[workspace]
members = [
  "crates/grid",
  "crates/core",
  "crates/bot",
  "crates/web-core",
  "crates/ml-core",
  "crates/py-core",
  "crates/playground",
  "crates/tree",
  "crates/move-finder",
  "crates/list-piece-consumption-patterns",
]
