[package]
name = "bot"
version = "0.1.0"
authors = ["Shintaro Seki <s2pch.luck@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "../core" }
grid = { path = "../grid" }
tree = { path = "../tree" }
rand = "0.8"
