name: Rust

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: extractions/setup-just@v1
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: make test

  py_core_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release -p py-core --verbose
    - name: Install
      run: ./script/install_py_core.sh release tmp
    - name: Upload detris-core.so
      uses: actions/upload-artifact@v1
      with:
        name: detris-core.so
        path: tmp/core.so
