name: Rust

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - run: pip install maturin
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: just test

#  py_core_release:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build
#      run: cargo build --release -p py-core --verbose
#    - name: Install
#      run: ./script/install_py_core.sh -p release tmp
#    - name: Upload detris-core.so
#      uses: actions/upload-artifact@v1
#      with:
#        name: detris-core.so
#        path: tmp/core.so
